### Create a new message
POST http://localhost:8080/api/create-message
Content-Type: application/json

{
  "userId": 1,
  "category": "sports",
  "country": "france",
  "content": "123456"
}

> {%
    client.test("It should return a successful status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
