name: Deploy backend to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t backend -f docker/production/backend-production.Dockerfile .

      - name: Tag Docker image
        run: docker tag backend registry.heroku.com/eu-talent-backend/web

      - name: Push docker image
        run: docker push registry.heroku.com/eu-talent-backend/web

      - name: Release on Heroku
        run: heroku container:release web --app eu-talent-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
